- name: download nginx
  yum:
    name: nginx
    state: present

- name: remove old docs
  file:
    path: /usr/share/nginx/html
    state: absent

- name: create htdoc directory
  file:
    path: usr/share/nginx/html
    state: directory

- name: downoad azure artifacts
  include_role:
    name: common
    tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /usr/share/nginx
    COMPONENT: frontend
    COMPONENT_ID: 60ee6a91-e102-4c5e-87a1-f41c517c4bd7

- name: start nginx service
  systemd:
    state: started
    name: nginx

