- name: download nginx
  yum:
    name: nginx
    state: present


- name: downoad azure artifacts
  include_role:
    name: common
    tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /usr/share/nginx/html
    COMPONENT: frontend
    COMPONENT_ID: 60ee6a91-e102-4c5e-87a1-f41c517c4bd7
    type: frontend

- name: update nginx config
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx service
  systemd:
    state: restarted
    name: nginx

