- name: instal nginx
  yum:
   name: nginx
   state: latest
- name: download a nginx docs
  get_url:
    url: "https://dev.azure.com/DevOps-Batches/f4b641c1-99db-46d1-8110-5c6c24ce2fb9/_apis/git/repositories/a781da9c-8fca-4605-8928-53c962282b74/items?path=%2F&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0&download=true"
    dest: /tmp/frontend.zip

- name: remove directory
  file:
    path: /usr/share/nginx/html
    state: absent

- name: unzip the docs
  unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

