- name: instal node js
  yum:
    name: nodejs
    state: present

- name: add application
  user:
    name: "{{ APP_USER }}"

- name: downoad azure artifacts
  include_role:
    name: common
    tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: cart
    COMPONENT_ID: 84230122-2433-403a-ba1e-d9f7e79fbdf6
    type: application

- name: start cart service
  systemd:
    name: cart
    state: restarted
    enabled: yes