- name: cpy Az repo file
  copy:
    src: az-cli.repo
    dest: /etc/yum.repos.d/az-cli.repo

- name: download azure cli
  yum:
    name: ["azure-cli", "libicu"]
    state: present

- name: install azure cli extension
  shell: az extension add --name azure-devops

- name: configure az login
  shell: echo {{ PAT }} | az devops login

#- name: grab latest version
#  shell: curl -s https://feeds.dev.azure.com/sushmitha771995/roboshop/_apis/packaging/Feeds/roboshop/Packages/84230122-2433-403a-ba1e-d9f7e79fbdf6/versions?api-version=6.1-preview.1 | jq '.value[] | .version+ " " +.views[].name' | grep Local | head -1 | xargs | awk  '{print $1}'
#  register: version
- name: grab the env and set the version for dev
  block:
    - name: grab version for dev
      shell: curl -s https://feeds.dev.azure.com/sushmitha771995/roboshop/_apis/packaging/Feeds/roboshop/Packages/84230122-2433-403a-ba1e-d9f7e79fbdf6/versions?api-version=6.1-preview.1 | jq '.value[] | .version+ " " +.views[].name' | grep Local | head -1 | xargs | awk  '{print $1}'
      register: version_dev
    - name: set version for dev
      set_fact:
        version: "{{ version_dev.stdout }}"
  when: ENV == "dev"

- name: grab the env and set the version for qa
  block:
    - name: grab version for prod
      shell: curl -s https://feeds.dev.azure.com/sushmitha771995/roboshop/_apis/packaging/Feeds/roboshop/Packages/84230122-2433-403a-ba1e-d9f7e79fbdf6/versions?api-version=6.1-preview.1 | jq '.value[] | .version+ " " +.views[].name' | grep PreRelease | head -1 | xargs | awk  '{print $1}'
      register: version_qa
    - name: set version for qa
      set_fact:
        version: "{{ version_qa.stdout }}"
  when: ENV == "qa"

- name: grab the env and set the version for
  block:
    - name: grp version for prod
      shell: curl -s https://feeds.dev.azure.com/sushmitha771995/roboshop/_apis/packaging/Feeds/roboshop/Packages/84230122-2433-403a-ba1e-d9f7e79fbdf6/versions?api-version=6.1-preview.1 | jq '.value[] | .version+ " " +.views[].name' | grep Release | head -1 | xargs | awk  '{print $1}'
      register: version_prod

    - name: set version for dev
      set_fact:
       version: "{{ version_prod.stdout  }}"
  when: ENV == "prod"

- name: Download azure artifacts , verison = {{version}} , ENV = {{ENV}}
  shell: az artifacts universal download \
    --organization "https://dev.azure.com/sushmitha771995/" \
    --project "144253b4-9c5f-41cd-a574-e33b077d69f7" \
    --scope project \
    --feed "roboshop" \
    --name "cart" \
    --version "{{version.stdout}}" \
    --path .
  args:
    chdir: /tmp
