- name: cpy Az repo file
  copy:
    src: az-cli.repo
    dest: /etc/yum.repos.d/az-cli.repo

- name: download azure cli
  yum:
    name: ["azure-cli", "libicu"]
    state: present

- name: install azure cli extension
  shell: az extension add --name azure-devops

- name: configure az login
  shell: echo {{ PAT }} | az devops login

- name: Download azure artifacts
  shell: az artifacts universal download \
    --organization "https://dev.azure.com/sushmitha771995/" \
    --project "144253b4-9c5f-41cd-a574-e33b077d69f7" \
    --scope project \
    --feed "roboshop" \
    --name "cart" \
    --version "0.0.1" \
    --path .
  args:
    chdir: /tmp
