- name: instal node js
  yum:
    name: nodejs
    state: present

- name: add application
  user:
    name: "{{ APP_USER }}"

- name: downoad azure artifacts
  include_role:
    name: common
    tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: user
    COMPONENT_ID: 51a23779-20c4-4b39-94c8-803124e3ac2c
    type: application

- name: Setup SystemD Service for User
  template:
    src: systemd.service
    dest: /etc/systemd/system/user.service

- name: start user service
  systemd:
    name: user
    state: restarted
    enabled: yes