- name: set up hostname
  include_role:
    name: common
    tasks_from: main.yml

- name: download mongodb repo
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: mongodb download
  yum:
    name: mongodb-org
    state: present

- name: update mongodb configuration file- network adress
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  systemd:
    name: mongod
    state: started
    enabled: yes

- name: downoad azure artifacts
  include_role:
     name: common
     tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /tmp/mongo
    COMPONENT: mongo
    COMPONENT_ID: 4d25e2b9-b185-4ca4-a419-fec6add19d7b
    type: database

- name: Load schema
  shell: mongo < /tmp/mongo/{{item}}.js
  loop:
    - catalogue
    - users

- name: start mongodb service
  systemd:
    name: mongod
    state: started
    enabled: yes
