- name: instal node js
  yum:
    name: nodejs
    state: present

- name: add application
  user:
    name: "{{ APP_USER }}"

- name: downoad azure artifacts
  include_role:
    name: common
    tasks_from: artifact.yml
  vars:
    ARTIFACT_PATH: /home/{{APP_USER}}/{{component}}
    COMPONENT: catalogue
    COMPONENT_ID: bfeffce2-f73e-47cb-8bf6-1647d981820a
    type: application