- name: roboshop
  hosts: all
  become: yes
  vars:
    APP_USER: roboshop
    DOMAIN: firstdevops.tk
  tasks:
    - name: import frontend Role
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend
    - name: import mongodb Role
      import_role:
        name: mongodb
      when: component == "mongodb"
      tags:
        - mongodb
    - name: import catalogue Role
      import_role:
        name: catalogue
      when: component == "catalogue"
      tags:
        - catalogue
    - name: import redis Role
        import_role:
          name: redis
        when: component == "redis"
        tags:
          - redis
    - name: import user Role
        import_role:
          name: user
        when: component == "user"
        tags:
          - user
    - name: import cart Role
        import_role:
          name: cart
        when: component == "cart"
        tags:
          - cart
    - name: import mysql Role
        import_role:
          name: mysql
        when: component == "mysql"
        tags:
          - mysql