- name: roboshop
  hosts: all
  become: yes
  vars:
    APP_USER: roboshop
  tasks:
    - name: import frontend Role
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend
    - name: import mongodb Role
      import_role:
          name: mongodb
      when: component == "mongodb"
      tags:
        - mongodb
- name: import catalogue Role
      import_role:
        name: cataogue
      when: component == "catalogue"
      tags:
        - catalogue