- name: roboshop
  hosts: all
  become: yes
  tasks:
    - name: import frontend Role
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend
    - name: import mongodb Role
      import_role:
          name: mongodb
      when: component == "mongodb"
      tags:
        - mongodb